// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../github.com/wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function CancelJob(jobID: string): $CancellablePromise<boolean> {
    return $Call.ByID(840311180, jobID);
}

export function ExportFile(sourcePath: string, destinationPath: string): $CancellablePromise<void> {
    return $Call.ByID(3092479727, sourcePath, destinationPath);
}

export function ExportReport(jobID: string, destinationPath: string): $CancellablePromise<void> {
    return $Call.ByID(902091367, jobID, destinationPath);
}

export function GetAudioDataURL(path: string): $CancellablePromise<string> {
    return $Call.ByID(1495760706, path);
}

export function GetDemoMetrics(): $CancellablePromise<$models.Metric[]> {
    return $Call.ByID(3947509723).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetDemoSummary(): $CancellablePromise<$models.SummaryItem[]> {
    return $Call.ByID(3929107274).then(($result: any) => {
        return $$createType3($result);
    });
}

export function GetJob(jobID: string): $CancellablePromise<$models.MasteringJob | null> {
    return $Call.ByID(3491431812, jobID).then(($result: any) => {
        return $$createType5($result);
    });
}

export function ListJobs(): $CancellablePromise<($models.MasteringJob | null)[]> {
    return $Call.ByID(3368901587).then(($result: any) => {
        return $$createType6($result);
    });
}

export function SetApp(app: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(3981453328, app);
}

export function StartMastering(req: $models.MasteringRequest): $CancellablePromise<string> {
    return $Call.ByID(1444517777, req);
}

// Private type creation functions
const $$createType0 = $models.Metric.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.SummaryItem.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $models.MasteringJob.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = $Create.Array($$createType5);
