// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class EngineCommand {
    "path": string;
    "args": string[];

    /** Creates a new EngineCommand instance. */
    constructor($$source: Partial<EngineCommand> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("args" in $$source)) {
            this["args"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EngineCommand instance from a string or object.
     */
    static createFrom($$source: any = {}): EngineCommand {
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("args" in $$parsedSource) {
            $$parsedSource["args"] = $$createField1_0($$parsedSource["args"]);
        }
        return new EngineCommand($$parsedSource as Partial<EngineCommand>);
    }
}

export class EngineDiagnostics {
    "engine": MasteringEngine;
    "binaries": { [_ in string]?: boolean };
    "simulated": boolean;
    "notes": string[];
    "command": EngineCommand;

    /** Creates a new EngineDiagnostics instance. */
    constructor($$source: Partial<EngineDiagnostics> = {}) {
        if (!("engine" in $$source)) {
            this["engine"] = MasteringEngine.$zero;
        }
        if (!("binaries" in $$source)) {
            this["binaries"] = {};
        }
        if (!("simulated" in $$source)) {
            this["simulated"] = false;
        }
        if (!("notes" in $$source)) {
            this["notes"] = [];
        }
        if (!("command" in $$source)) {
            this["command"] = (new EngineCommand());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EngineDiagnostics instance from a string or object.
     */
    static createFrom($$source: any = {}): EngineDiagnostics {
        const $$createField1_0 = $$createType1;
        const $$createField3_0 = $$createType0;
        const $$createField4_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("binaries" in $$parsedSource) {
            $$parsedSource["binaries"] = $$createField1_0($$parsedSource["binaries"]);
        }
        if ("notes" in $$parsedSource) {
            $$parsedSource["notes"] = $$createField3_0($$parsedSource["notes"]);
        }
        if ("command" in $$parsedSource) {
            $$parsedSource["command"] = $$createField4_0($$parsedSource["command"]);
        }
        return new EngineDiagnostics($$parsedSource as Partial<EngineDiagnostics>);
    }
}

export enum MasteringEngine {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    EngineHybrid = "hybrid",
    EngineClassic = "classic",
};

export class MasteringJob {
    "id": string;
    "status": string;
    "progress": number;
    "message": string;
    "error": string;
    "inputPath": string;
    "startedAt": string;
    "completedAt": string;
    "result"?: MasteringResult | null;

    /** Creates a new MasteringJob instance. */
    constructor($$source: Partial<MasteringJob> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("progress" in $$source)) {
            this["progress"] = 0;
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }
        if (!("error" in $$source)) {
            this["error"] = "";
        }
        if (!("inputPath" in $$source)) {
            this["inputPath"] = "";
        }
        if (!("startedAt" in $$source)) {
            this["startedAt"] = "";
        }
        if (!("completedAt" in $$source)) {
            this["completedAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MasteringJob instance from a string or object.
     */
    static createFrom($$source: any = {}): MasteringJob {
        const $$createField8_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("result" in $$parsedSource) {
            $$parsedSource["result"] = $$createField8_0($$parsedSource["result"]);
        }
        return new MasteringJob($$parsedSource as Partial<MasteringJob>);
    }
}

export class MasteringOptions {
    "targetLoudnessMode": string;
    "targetLoudness": number;
    "ceilingMode": string;
    "ceiling": number;
    "oversampling": string;
    "automaticMastering": boolean;
    "automaticLevel": number;
    "outputFormat": string;
    "sampleRate": string;
    "lowCutHz": number;
    "highCutHz": number;

    /** Creates a new MasteringOptions instance. */
    constructor($$source: Partial<MasteringOptions> = {}) {
        if (!("targetLoudnessMode" in $$source)) {
            this["targetLoudnessMode"] = "";
        }
        if (!("targetLoudness" in $$source)) {
            this["targetLoudness"] = 0;
        }
        if (!("ceilingMode" in $$source)) {
            this["ceilingMode"] = "";
        }
        if (!("ceiling" in $$source)) {
            this["ceiling"] = 0;
        }
        if (!("oversampling" in $$source)) {
            this["oversampling"] = "";
        }
        if (!("automaticMastering" in $$source)) {
            this["automaticMastering"] = false;
        }
        if (!("automaticLevel" in $$source)) {
            this["automaticLevel"] = 0;
        }
        if (!("outputFormat" in $$source)) {
            this["outputFormat"] = "";
        }
        if (!("sampleRate" in $$source)) {
            this["sampleRate"] = "";
        }
        if (!("lowCutHz" in $$source)) {
            this["lowCutHz"] = 0;
        }
        if (!("highCutHz" in $$source)) {
            this["highCutHz"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MasteringOptions instance from a string or object.
     */
    static createFrom($$source: any = {}): MasteringOptions {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MasteringOptions($$parsedSource as Partial<MasteringOptions>);
    }
}

export class MasteringRequest {
    "inputPath": string;
    "outputDir": string;
    "engine": MasteringEngine;
    "options": MasteringOptions;

    /** Creates a new MasteringRequest instance. */
    constructor($$source: Partial<MasteringRequest> = {}) {
        if (!("inputPath" in $$source)) {
            this["inputPath"] = "";
        }
        if (!("outputDir" in $$source)) {
            this["outputDir"] = "";
        }
        if (!("engine" in $$source)) {
            this["engine"] = MasteringEngine.$zero;
        }
        if (!("options" in $$source)) {
            this["options"] = (new MasteringOptions());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MasteringRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): MasteringRequest {
        const $$createField3_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("options" in $$parsedSource) {
            $$parsedSource["options"] = $$createField3_0($$parsedSource["options"]);
        }
        return new MasteringRequest($$parsedSource as Partial<MasteringRequest>);
    }
}

export class MasteringResult {
    "outputPath": string;
    "summary": SummaryItem[];
    "metrics": Metric[];
    "warnings": string[];
    "diagnostics": EngineDiagnostics;

    /** Creates a new MasteringResult instance. */
    constructor($$source: Partial<MasteringResult> = {}) {
        if (!("outputPath" in $$source)) {
            this["outputPath"] = "";
        }
        if (!("summary" in $$source)) {
            this["summary"] = [];
        }
        if (!("metrics" in $$source)) {
            this["metrics"] = [];
        }
        if (!("warnings" in $$source)) {
            this["warnings"] = [];
        }
        if (!("diagnostics" in $$source)) {
            this["diagnostics"] = (new EngineDiagnostics());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MasteringResult instance from a string or object.
     */
    static createFrom($$source: any = {}): MasteringResult {
        const $$createField1_0 = $$createType7;
        const $$createField2_0 = $$createType9;
        const $$createField3_0 = $$createType0;
        const $$createField4_0 = $$createType10;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("summary" in $$parsedSource) {
            $$parsedSource["summary"] = $$createField1_0($$parsedSource["summary"]);
        }
        if ("metrics" in $$parsedSource) {
            $$parsedSource["metrics"] = $$createField2_0($$parsedSource["metrics"]);
        }
        if ("warnings" in $$parsedSource) {
            $$parsedSource["warnings"] = $$createField3_0($$parsedSource["warnings"]);
        }
        if ("diagnostics" in $$parsedSource) {
            $$parsedSource["diagnostics"] = $$createField4_0($$parsedSource["diagnostics"]);
        }
        return new MasteringResult($$parsedSource as Partial<MasteringResult>);
    }
}

export class Metric {
    "name": string;
    "original": string;
    "mastered": string;
    "percentOriginal": number;
    "percentMastered": number;

    /** Creates a new Metric instance. */
    constructor($$source: Partial<Metric> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("original" in $$source)) {
            this["original"] = "";
        }
        if (!("mastered" in $$source)) {
            this["mastered"] = "";
        }
        if (!("percentOriginal" in $$source)) {
            this["percentOriginal"] = 0;
        }
        if (!("percentMastered" in $$source)) {
            this["percentMastered"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Metric instance from a string or object.
     */
    static createFrom($$source: any = {}): Metric {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Metric($$parsedSource as Partial<Metric>);
    }
}

export class ProgressEvent {
    "jobId": string;
    "percent": number;
    "message": string;

    /** Creates a new ProgressEvent instance. */
    constructor($$source: Partial<ProgressEvent> = {}) {
        if (!("jobId" in $$source)) {
            this["jobId"] = "";
        }
        if (!("percent" in $$source)) {
            this["percent"] = 0;
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProgressEvent instance from a string or object.
     */
    static createFrom($$source: any = {}): ProgressEvent {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProgressEvent($$parsedSource as Partial<ProgressEvent>);
    }
}

export class SummaryItem {
    "label": string;
    "value": string;

    /** Creates a new SummaryItem instance. */
    constructor($$source: Partial<SummaryItem> = {}) {
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("value" in $$source)) {
            this["value"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SummaryItem instance from a string or object.
     */
    static createFrom($$source: any = {}): SummaryItem {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SummaryItem($$parsedSource as Partial<SummaryItem>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $Create.Map($Create.Any, $Create.Any);
const $$createType2 = EngineCommand.createFrom;
const $$createType3 = MasteringResult.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = MasteringOptions.createFrom;
const $$createType6 = SummaryItem.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = Metric.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = EngineDiagnostics.createFrom;
